from backend.agents.base import BaseAgent
from backend.services.model_router import TaskComplexity

class WebDesignerAgent(BaseAgent):
    def __init__(self):
        super().__init__("WebDesigner", TaskComplexity.HEAVY)

    async def run(self, prompt: str) -> dict:
        model = self.get_model()
        result = f"// Next.js + Tailwind Component\n// Generated by {model}\n\nexport default function Component() {{ return <div className='p-4'>Generated for: {prompt}</div> }}"
        return {"output": result, "model_used": model}

web_designer_agent = WebDesignerAgent()
